outDir: ./output
useMySQL: false
server: null # server name array if specific servers
MySQLConfig:
  host: mysql
  user: tx3
  database: tx3
  password: my_password
proxy:
  useProxy: false
  proxySource:
    - "http://www.89ip.cn/tqdl.html?api=1&num=9999"
    - "http://www.66ip.cn/mo.php?tqsl=9999"
  timeout: 10000